apiVersion: v1
 kind: ConfigMap
 metadata:
   name: mongo-key

 data:
   mongo.key: |
     ahaksdnqsakdqnajhvckqaafnxasxaxaxmaskdadadsasfsdsdfsf
     schcacnctcacncuadasdadadfbsasddfbadadwsioweewvaas
     dfasasakjsvnaa