apiVersion: v1
kind: ConfigMap
metadata:
  name: rair-stream-env
data:
  PRODUCTION: "true"
  PINATA_KEY: ""
  GCP_PROJECT_ID: rair-market
  GCP_IMAGE_BUCKET_NAME: rair_images
  GCP_VIDEO_BUCKET_NAME: rair-videos
  GCP_GATEWAY: https://storage.googleapis.com
  IPFS_SERVICE: pinata
  IPFS_GATEWAY: http://rairipfs:8080/ipfs
  PINATA_GATEWAY: https://rair.mypinata.cloud/ipfs
  MONGO_LOG_COLLECTION: Log
  LOG_LEVEL: debug
  MEDIA_SERVICE_PORT: "5002"
  BASE_RAIRNODE_URL: "http://rairnode:5000"
  USE_X509_CERT_AUTH: "false"
  IPFS_API: http://rairipfs:5001
  VAULT_URL: https://primary-dev.vault.9871e6c3-b0b9-479a-b392-eb69322d192a.aws.hashicorp.cloud:8200
  VAULT_MEDIA_SERVICE_APP_ROLE_ID: ""
  VAULT_MEDIA_SERVICE_APP_ROLE_SECRET_ID: ""
  VAULT_MEDIA_SERVICE_use_x509_cert_auth: "false"
  SERVICE_HOST: https://ms.rair.market
  REDIS_HOST: rair-redis
  REDIS_PORT: "6379"