version: "2"

services:
  nginx:
    build: ./nginx
    image: devcomanda/nginx
    env_file:
      - ./config.env
    volumes:
      - devcomanda_nginx_ssl:/etc/nginx/ssl
      - devcomanda_certbot_certs:/etc/letsencrypt
      - test1_devcomanda_com_certbot:/var/www/certbot/test1.devcomanda.com
      - test2_devcomanda_com_certbot:/var/www/certbot/test2.devcomanda.com
      - ./html:/var/www/html/test1.devcomanda.com
      - ./html:/var/www/html/test2.devcomanda.com
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    image: devcomanda/certbot
    env_file:
      - ./config.env
    volumes:
      - devcomanda_certbot_certs:/etc/letsencrypt
      - test1_devcomanda_com_certbot:/var/www/certbot/localhost
    depends_on:
      - nginx

  cron:
    build: ./cron
    image: devcomanda/cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    depends_on:
      - nginx
      - certbot

volumes:
  devcomanda_nginx_ssl:
    external: true
  devcomanda_certbot_certs:
    external: true
  test1_devcomanda_com_certbot:
  test2_devcomanda_com_certbot:
